---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-sidecar
  namespace: kube-system
  labels:
    app: k8s-sidecar-injector
    track: test
data:
  sb-sidecar: |
    name: sb-sidecar
    serviceAccountName: quick-start-application
    containers:
      - name: secretless
        image: cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        args: ["-f", "/etc/secretless/secretless.yml"]
    volumeMounts:
    - name: config
      mountPath: /etc/secretless
      readOnly: true
    # - name: service-account-token
    #   mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    #   readOnly: true
    volumes:
    - name: config
      configMap:
        name: quick-start-application-secretless-config
    # - name: service-account-token
    #   secret:
    #     name: serviceaccount-token-sb-sidecar
